name: Deploy AFT Bootstrap

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.tf'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::803356297187:role/AFTGitHubRole
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Import existing resources (run only once)
        run: |
          # DynamoDB lock table
          if ! terraform state show module.aft.module.aft_backend.aws_dynamodb_table.lock-table >/dev/null 2>&1; then
            terraform import module.aft.module.aft_backend.aws_dynamodb_table.lock-table aft-backend-803356297187-lock-table || true
          fi

          # S3 backend bucket
          if ! terraform state show module.aft.module.aft_backend.aws_s3_bucket.primary-backend-bucket >/dev/null 2>&1; then
            terraform import module.aft.module.aft_backend.aws_s3_bucket.primary-backend-bucket aft-backend-803356297187-primary-region || true
          fi

          # IAM Roles
          if ! terraform state show module.aft.module.aft_iam_roles.module.aft_exec_role.aws_iam_role.role >/dev/null 2>&1; then
            terraform import module.aft.module.aft_iam_roles.module.aft_exec_role.aws_iam_role.role AWSAFTExecution || true
          fi

          if ! terraform state show module.aft.module.aft_iam_roles.module.aft_service_role.aws_iam_role.role >/dev/null 2>&1; then
            terraform import module.aft.module.aft_iam_roles.module.aft_service_role.aws_iam_role.role AWSAFTService || true
          fi

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
